In [1]:
import geopandas as gpd

In [2]:
from gpt_morpho_analysis import load_buildings, load_GBA_buildings


buildings_GBA = load_GBA_buildings(epsg=32632)
#buildings = load_buildings(epsg=32632, default_levels=3)

✓ Loaded 34714 GBA buildings

In [3]:
from gpt_morpho_analysis import create_building_statistic


create_building_statistic(buildings_GBA, "GBA Building statistics for Würzburg")

✓ Building classification visualization saved to .//building_height_classification.png

In [6]:
# buildings stats
print(buildings["height_calc"].mean())
print(buildings["height_calc"].max())
print(buildings["height_calc"].min())

12.97113860917327
80.0
0.2

In [2]:
buildings_df = gpd.read_file("./data/de_cuyan/wuerzburg_Buildings.gpkg")

In [3]:
buildings_df

,element,id,name,geometry
0,node,664745957,None,POINT (9.91686 49.79138)
1,relation,7074,Residenz Würzburg,"POLYGON ((9.93883 49.79301, 9.93886 49.79307, ..."
2,relation,166012,Kilianeum,"POLYGON ((9.93633 49.78965, 9.93617 49.79016, ..."
3,relation,225641,None,"POLYGON ((9.93023 49.79769, 9.93023 49.79769, ..."
4,relation,901492,St.Burkardus-Haus,"POLYGON ((9.93217 49.79282, 9.93183 49.79282, ..."
...,...,...,...,...
2966,way,1367954511,Esso Snack & Shop,"POLYGON ((9.92098 49.80319, 9.921 49.80321, 9...."
2967,way,1408563703,None,"POLYGON ((9.93439 49.79391, 9.93473 49.79385, ..."
2968,way,1408563704,None,"POLYGON ((9.93502 49.79419, 9.93511 49.79418, ..."
2969,way,1408563705,None,"POLYGON ((9.93478 49.79398, 9.93484 49.79423, ..."
2970,way,1408563714,None,"POLYGON ((9.93317 49.7922, 9.93313 49.79221, 9..."

In [4]:
wue_df = gpd.read_file("./data/osm/wue_buildings_and_landuse.gpkg")

In [5]:
wue_df["building"].describe()

count     31679
unique       85
top         yes
freq      11272
Name: building, dtype: object

In [6]:
wue_df["building"]

0               yes
1             house
2               yes
3           carport
4        apartments
            ...
33677         house
33678    apartments
33679          None
33680          None
33681       toilets
Name: building, Length: 33682, dtype: object

In [7]:
wue_df

,element,id,addr:city,addr:housenumber,addr:postcode,addr:street,amenity,brand,brand:wikidata,building,...,name:hu,name:it,name:ja,name:pl,ref:whc,whc:inscription_date,leaf_cycle,emergency_telephone_code,order,geometry
0,node,339407734,Würzburg,106,97078,Versbacher Straße,fuel,Esso,Q867662,yes,...,None,None,None,None,None,None,None,None,None,POINT (9.96347 49.81616)
1,node,477372238,None,None,None,None,None,None,None,house,...,None,None,None,None,None,None,None,None,None,POINT (9.94901 49.77581)
2,node,664745957,None,None,None,None,None,None,None,yes,...,None,None,None,None,None,None,None,None,None,POINT (9.91686 49.79138)
3,node,1299572531,None,None,None,None,None,None,None,carport,...,None,None,None,None,None,None,None,None,None,POINT (9.93844 49.77954)
4,node,1923846741,Würzburg,10,97074,Barbarastraße,None,None,None,apartments,...,None,None,None,None,None,None,None,None,None,POINT (9.95397 49.79612)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33677,way,1452874424,Würzburg,35,97076,Riedstraße,None,None,None,house,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.99041 49.81277, 9.99053 49.8127, 9..."
33678,way,1454523378,None,6,None,Odenwaldstraße,None,None,None,apartments,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.98431 49.81211, 9.98444 49.81219, ..."
33679,way,1455452327,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.97797 49.75096, 9.97768 49.75087, ..."
33680,way,1455452328,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.97941 49.74856, 9.97942 49.74862, ..."
33681,way,1456554671,None,None,None,None,toilets,None,None,toilets,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.9455 49.79631, 9.94552 49.79637, 9..."

In [ ]:
buildings_with_height = wue_df.dropna(subset=["height"])
buildings_with_height

,element,id,addr:city,addr:housenumber,addr:postcode,addr:street,amenity,brand,brand:wikidata,building,...,name:hu,name:it,name:ja,name:pl,ref:whc,whc:inscription_date,leaf_cycle,emergency_telephone_code,order,geometry
18,relation,7074,Würzburg,2,97070,Residenzplatz,None,None,None,castle,...,Würzburgi püspöki palota,Viurcburgo rūmai,ヴュルツブルクのレジデンツ,Rezydencja w Würzburgu,169,1981,None,None,None,"POLYGON ((9.93883 49.79301, 9.93886 49.79307, ..."
24,relation,289924,Würzburg,1,97074,Wittelsbacherplatz,None,None,None,university,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.95157 49.78613, 9.9516 49.78611, 9..."
28,relation,901492,None,1,None,Am Bruderhof,conference_centre,None,None,church,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.93217 49.79282, 9.93183 49.79282, ..."
76,relation,4743092,None,None,None,None,None,None,None,yes,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.93794 49.79307, 9.93799 49.79307, ..."
97,relation,14093361,None,None,None,None,None,None,None,retail,...,None,None,None,None,None,None,None,None,None,"MULTIPOLYGON (((9.92927 49.79474, 9.92926 49.7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32460,way,1210692913,None,None,None,None,None,None,None,apartments,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.92478 49.79272, 9.92475 49.79283, ..."
32461,way,1210692915,None,None,None,None,None,None,None,apartments,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.92483 49.79248, 9.92482 49.79254, ..."
32462,way,1210692916,None,None,None,None,None,None,None,apartments,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.92481 49.79257, 9.92479 49.79266, ..."
32685,way,1252130750,Würzburg,None,97070,Unterer Markt,None,None,None,retail,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.92981 49.79448, 9.92979 49.79448, ..."
32849,way,1289396666,Würzburg,16l,97074,Am Hubland,None,None,None,apartments,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.96617 49.7794, 9.96617 49.77945, 9..."

In [ ]:
buildings_with_levels = wue_df.dropna(subset=["building:levels"])
buildings_with_levels

,element,id,addr:city,addr:housenumber,addr:postcode,addr:street,amenity,brand,brand:wikidata,building,...,name:hu,name:it,name:ja,name:pl,ref:whc,whc:inscription_date,leaf_cycle,emergency_telephone_code,order,geometry
4,node,1923846741,Würzburg,10,97074,Barbarastraße,None,None,None,apartments,...,None,None,None,None,None,None,None,None,None,POINT (9.95397 49.79612)
5,node,1923846742,Würzburg,8,97074,Barbarastraße,None,None,None,apartments,...,None,None,None,None,None,None,None,None,None,POINT (9.95372 49.79614)
18,relation,7074,Würzburg,2,97070,Residenzplatz,None,None,None,castle,...,Würzburgi püspöki palota,Viurcburgo rūmai,ヴュルツブルクのレジデンツ,Rezydencja w Würzburgu,169,1981,None,None,None,"POLYGON ((9.93883 49.79301, 9.93886 49.79307, ..."
24,relation,289924,Würzburg,1,97074,Wittelsbacherplatz,None,None,None,university,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.95157 49.78613, 9.9516 49.78611, 9..."
29,relation,1299018,None,22,97082,Friedrichstraße,None,None,None,school,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.91203 49.79761, 9.91203 49.79764, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33255,way,1366625702,None,None,None,None,None,None,None,commercial,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.99178 49.82401, 9.99179 49.82401, ..."
33265,way,1368996600,Würzburg,3,97080,Sankt-Josef-Straße,None,None,None,civic,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.92073 49.82648, 9.92087 49.82647, ..."
33266,way,1372475929,None,None,None,None,None,None,None,house,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.92263 49.81181, 9.92252 49.8119, 9..."
33340,way,1388261166,Würzburg,2,97080,Josef-Schneider-Straße,None,None,None,hospital,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.95575 49.80043, 9.95573 49.80029, ..."
33571,way,1431974030,Würzburg,25,97084,Würzburger Straße,None,None,None,house,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.9632 49.72029, 9.96325 49.72022, 9..."

In [ ]:
buildings_with_height_or_levels = wue_df.dropna(
    subset=["height", "building:levels"], how="all"
)

In [42]:
buildings_with_height_or_levels

,element,id,addr:city,addr:housenumber,addr:postcode,addr:street,amenity,brand,brand:wikidata,building,...,name:hu,name:it,name:ja,name:pl,ref:whc,whc:inscription_date,leaf_cycle,emergency_telephone_code,order,geometry
4,node,1923846741,Würzburg,10,97074,Barbarastraße,None,None,None,apartments,...,None,None,None,None,None,None,None,None,None,POINT (9.95397 49.79612)
5,node,1923846742,Würzburg,8,97074,Barbarastraße,None,None,None,apartments,...,None,None,None,None,None,None,None,None,None,POINT (9.95372 49.79614)
18,relation,7074,Würzburg,2,97070,Residenzplatz,None,None,None,castle,...,Würzburgi püspöki palota,Viurcburgo rūmai,ヴュルツブルクのレジデンツ,Rezydencja w Würzburgu,169,1981,None,None,None,"POLYGON ((9.93883 49.79301, 9.93886 49.79307, ..."
24,relation,289924,Würzburg,1,97074,Wittelsbacherplatz,None,None,None,university,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.95157 49.78613, 9.9516 49.78611, 9..."
28,relation,901492,None,1,None,Am Bruderhof,conference_centre,None,None,church,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.93217 49.79282, 9.93183 49.79282, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33255,way,1366625702,None,None,None,None,None,None,None,commercial,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.99178 49.82401, 9.99179 49.82401, ..."
33265,way,1368996600,Würzburg,3,97080,Sankt-Josef-Straße,None,None,None,civic,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.92073 49.82648, 9.92087 49.82647, ..."
33266,way,1372475929,None,None,None,None,None,None,None,house,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.92263 49.81181, 9.92252 49.8119, 9..."
33340,way,1388261166,Würzburg,2,97080,Josef-Schneider-Straße,None,None,None,hospital,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.95575 49.80043, 9.95573 49.80029, ..."
33571,way,1431974030,Würzburg,25,97084,Würzburger Straße,None,None,None,house,...,None,None,None,None,None,None,None,None,None,"POLYGON ((9.9632 49.72029, 9.96325 49.72022, 9..."

In [12]:
import numpy as np
import re

In [55]:
# r'?<!\S)[+-]?\d+(?:\.\d+)?(?:\s*[a-zA-Z]+)?\b'
# r'([+-]?\d+(?:\.\d+)?)\s*m'

In [56]:
buildings_with_height_or_levels["height"]

4        None
5        None
18       23 m
24         15
28         11
         ...
33255    None
33265    None
33266    None
33340    None
33571    None
Name: height, Length: 5422, dtype: object

In [ ]:
def parse_height(row, col: str = "height") -> float | None:
    value = row[col]
    if isinstance(value, int):
        return float(value)
    if isinstance(value, float):
        return value
    if isinstance(value, str):
        match = re.search(r"([+-]?\d+(?:\.\d+)?)\s*m", value)
        if match:
            return float(match.group(1))
    return np.nan

In [ ]:
def parse_height_2(row, col: str = "height") -> float | None:
    value = row[col]
    if isinstance(value, int):
        return float(value)
    if isinstance(value, float):
        return value
    if isinstance(value, str):
        match = re.search(r"([+-]?\d+(?:\.\d+)?)\s*m", value)
        if match:
            return float(match.group(1))
    return None

In [ ]:
buildings_with_height_or_levels["height_corrected"] = (
    buildings_with_height_or_levels.apply(parse_height_2, axis=0)
)

In [75]:
buildings_with_height_or_levels["height_corrected"]

4                  NaN
5                  NaN
18                 NaN
24                 NaN
28                 NaN
                    ..
33266              NaN
33340              NaN
33571              NaN
height_corrected   NaN
height             NaN
Name: height_corrected, Length: 5424, dtype: float64

In [ ]:
DEFAULT_BUILDING_HEIGHT = 12

In [18]:
import pandas as pd

In [ ]:
buildings_with_height_or_levels["height_c"] = pd.to_numeric(
    buildings_with_height_or_levels["height"], errors="coerce"
).fillna(DEFAULT_BUILDING_HEIGHT)

/run/media/feds/2309E02F47F328C5/EAGLE/Urban_AZwick/FinalMeasurements/.venv/lib/python3.13/site-packages/geopandas/geodataframe.py:1968: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [44]:
buildings_with_height_or_levels["height_c"]

4        12.0
5        12.0
18       12.0
24       15.0
28       11.0
         ...
33255    12.0
33265    12.0
33266    12.0
33340    12.0
33571    12.0
Name: height_c, Length: 5422, dtype: float64

In [ ]:
import numpy as np

DEFAULT_ROOF_LEVEL_HEIGHT = 3
DEFAULT_LEVEL_HEIGHT = 4
DEFAULT_BUILDING_HEIGHT = 12


def height_calculator(df) -> float:
    height = 0

    # building height
    if df["height"] != np.nan:
        height += df["height"]
    elif df["building:levels"] != np.nan:
        height += df["building:levels"] * DEFAULT_LEVEL_HEIGHT
    if height != 0:  # if we got a height, add a roof height
        if df["roof:height"] != np.nan:
            height += df["roof:height"]
        elif df["roof:levels"] != np.nan:
            height += df["roof:levels"] * DEFAULT_ROOF_LEVEL_HEIGHT
        return height
    return DEFAULT_BUILDING_HEIGHT

In [ ]:
buildings_with_height_or_levels["adjusted_height"] = (
    buildings_with_height_or_levels.map(height_calculator)
)

TypeError: string indices must be integers, not 'str'

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [13]:
%matplotlib qt

In [ ]:
fix, ax = plt.subplots(figsize=(10, 10))
buildings_with_height_or_levels.plot(ax=ax, color="blue")
wue_df[wue_df["building"] != np.nan].plot(ax=ax, color="red", alpha=0.25)
plt.tight_layout()
plt.show()

In [43]:
np.mean(buildings_with_height_or_levels["height"])

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
# from this point on, assume building height 12m (or mean of city) for the nodata values

# vis

In [46]:
buildings_with_height_or_levels["height_c"]

4        12.0
5        12.0
18       12.0
24       15.0
28       11.0
         ...
33255    12.0
33265    12.0
33266    12.0
33340    12.0
33571    12.0
Name: height_c, Length: 5422, dtype: float64

In [47]:
VIEW_LATITUDE = 49.7913
VIEW_LONGITUDE = 9.9536

In [48]:
import os

In [49]:
import shapely as shp

In [ ]:
buildings_with_height_or_levels.geometry.fillna(
    shp.geometry.Polygon([[1, 1], [1, 1], [1, 1], [1, 1]])
)

4                                 POINT (9.95397 49.79612)
5                                 POINT (9.95372 49.79614)
18       POLYGON ((9.93883 49.79301, 9.93886 49.79307, ...
24       POLYGON ((9.95157 49.78613, 9.9516 49.78611, 9...
28       POLYGON ((9.93217 49.79282, 9.93183 49.79282, ...
                               ...
33255    POLYGON ((9.99178 49.82401, 9.99179 49.82401, ...
33265    POLYGON ((9.92073 49.82648, 9.92087 49.82647, ...
33266    POLYGON ((9.92263 49.81181, 9.92252 49.8119, 9...
33340    POLYGON ((9.95575 49.80043, 9.95573 49.80029, ...
33571    POLYGON ((9.9632 49.72029, 9.96325 49.72022, 9...
Name: geometry, Length: 5422, dtype: geometry

In [55]:
buildings_with_height_or_levels

,element,id,addr:city,addr:housenumber,addr:postcode,addr:street,amenity,brand,brand:wikidata,building,...,name:it,name:ja,name:pl,ref:whc,whc:inscription_date,leaf_cycle,emergency_telephone_code,order,geometry,height_c
4,node,1923846741,Würzburg,10,97074,Barbarastraße,None,None,None,apartments,...,None,None,None,None,None,None,None,None,POINT (9.95397 49.79612),12.0
5,node,1923846742,Würzburg,8,97074,Barbarastraße,None,None,None,apartments,...,None,None,None,None,None,None,None,None,POINT (9.95372 49.79614),12.0
18,relation,7074,Würzburg,2,97070,Residenzplatz,None,None,None,castle,...,Viurcburgo rūmai,ヴュルツブルクのレジデンツ,Rezydencja w Würzburgu,169,1981,None,None,None,"POLYGON ((9.93883 49.79301, 9.93886 49.79307, ...",12.0
24,relation,289924,Würzburg,1,97074,Wittelsbacherplatz,None,None,None,university,...,None,None,None,None,None,None,None,None,"POLYGON ((9.95157 49.78613, 9.9516 49.78611, 9...",15.0
28,relation,901492,None,1,None,Am Bruderhof,conference_centre,None,None,church,...,None,None,None,None,None,None,None,None,"POLYGON ((9.93217 49.79282, 9.93183 49.79282, ...",11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33255,way,1366625702,None,None,None,None,None,None,None,commercial,...,None,None,None,None,None,None,None,None,"POLYGON ((9.99178 49.82401, 9.99179 49.82401, ...",12.0
33265,way,1368996600,Würzburg,3,97080,Sankt-Josef-Straße,None,None,None,civic,...,None,None,None,None,None,None,None,None,"POLYGON ((9.92073 49.82648, 9.92087 49.82647, ...",12.0
33266,way,1372475929,None,None,None,None,None,None,None,house,...,None,None,None,None,None,None,None,None,"POLYGON ((9.92263 49.81181, 9.92252 49.8119, 9...",12.0
33340,way,1388261166,Würzburg,2,97080,Josef-Schneider-Straße,None,None,None,hospital,...,None,None,None,None,None,None,None,None,"POLYGON ((9.95575 49.80043, 9.95573 49.80029, ...",12.0
33571,way,1431974030,Würzburg,25,97084,Würzburger Straße,None,None,None,house,...,None,None,None,None,None,None,None,None,"POLYGON ((9.9632 49.72029, 9.96325 49.72022, 9...",12.0

In [54]:
buildings_with_height_or_levels["geometry"].count()

np.int64(5422)

In [ ]:
import pydeck as pdk

# Define the 3D building layer
building_layer = pdk.Layer(
    "PolygonLayer",
    data=buildings_with_height_or_levels,
    get_polygon="geometry.exterior.coords",  # This is where we use the geopandas geometry
    get_elevation="height_c",
    elevation_scale=1,
    get_fill_color=[200, 200, 255, 180],  # Light blue buildings
    pickable=True,
    auto_highlight=True,
    extruded=True,
)

# Set the view state with the initial camera position and pitch for a 3D effect
view_state = pdk.ViewState(
    latitude=VIEW_LATITUDE,
    longitude=VIEW_LONGITUDE,
    zoom=1,  # 14
    pitch=45,
    bearing=0,
)

# Create the Pydeck map
r = pdk.Deck(
    layers=[building_layer],
    initial_view_state=view_state,
    tooltip={"text": "Building Height: {height_c} meters"},
    map_style="mapbox://styles/mapbox/light-v10",  # Requires Mapbox token for non-default styles
)

# You may need a Mapbox API token for non-default map styles.
# Set it as an environment variable (e.g., MAPBOX_API_KEY) or use a free style like:
# map_style='basemaps.cartocdn.com'

# Save the interactive map to an HTML file
output_path = "interactive_3d_map.html"
r.to_html(output_path)

print(f"Interactive 3D map saved to {os.path.abspath(output_path)}")
print("Open the HTML file in your web browser to view the map.")

Interactive 3D map saved to /run/media/feds/2309E02F47F328C5/EAGLE/Urban_AZwick/FinalMeasurements/interactive_3d_map.html
Open the HTML file in your web browser to view the map.